{{- if and .Values.auth.enabled .Values.auth.hmac.enabled .Values.auth.hmac.secret (not .Values.auth.hmac.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "piko.fullname" . }}-hmac-secret
  labels:
    {{- include "piko.labels" . | nindent 4 }}
type: Opaque
data:
  hmac-secret: {{ .Values.auth.hmac.secret | b64enc }}
{{- end }}
